language: java
sudo: "required
  env: "TRAVIS_NODE_VERSION=\"6\""
  before_install: [
    "nvm install node"
  ]
  before_script: [
    "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -",
    "sudo apt-get install nodejs",
    "sudo apt-get install build-essential"
  ]
sudo: false
install: true
addons:
  sonarcloud:
    organization: "marco76-github"
    token:
      secure: "Cv51uUtkwe/htvxf4MgzA3CGQqY3vgmDlwsP3/egrJnRbIYHbAFUbb8zwANOGbcERltvIkuxBo5NqCIl7UTzUixhlYHhfpRmu9Df66xqmzD+3EUJ2rpGJf5nJXe3wZLvmtVPYq5TiiGs4NJb+o80eBwyiZEeplK/TcZLOOtREFI+xchojAhiIa6ZByuJ4Wv0boLC1wR6yxM4jGKXipunoCZq7rD7C+T+b1KRm9zN59rjWcxvXeqLwkrze1uOBsAw1d8Ng0+9ZlqGs2NofMUL6ecQNyISA29QnDD4rpVdjoGmorjLQIlDzeKPIj3B8hPBzylDvZ8vlQcU+dc9MYnHjGyOmPfCb3nic53mquonWzS3OZOasijVZ9CGaQTWhb4DCYs6cEj07VPJg+aMfPB8AfPdeq9LJuPquI/QJ4yX+GEKviAHh/bfeFU58IeB3wV491tni3/8c4LS2DfB+3uunm6ULtLweJznK9GF8SmM8FESU5jhs2iS/nBOPY0eP2vRm2WrJhzXjxwY/19XBM/DRcFSl+ko3sqd3QINZxRyEZhuc41SY1b2igrDiz40+hdH4k0hNvakBczmbbM87Qbb4U0E+CjXciN2x9VU8FMzQo+YBr+LnYYMlj6pSoE9lMmjPuNirhIldt9TqDxMEFyp/YTlKAC7wAZlZYSu/W9uC9o="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'